import { boolean, integer, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const scanConfig = pgTable('scan_config', {
  id: integer('id').primaryKey().default(1),
  productName: text('product_name').notNull().default('REPLAICED'),
  productUrl: text('product_url').notNull().default('https://replaiced.co'),
  productDescription: text('product_description').notNull().default('A tool that scores how at-risk your job is from AI replacement, suggests skills to learn to stay ahead, and recommends potential career pivots based on your resume.'),
  productKeywords: text('product_keywords').array().notNull().default(['AI replacement', 'job displacement', 'career pivot', 'AI-proofing']),
  icpTitles: text('icp_titles').array().notNull().default(['knowledge worker', 'software engineer', 'marketer', 'designer', 'product manager', 'analyst']),
  searchQueries: text('search_queries').array().notNull(),
  scansPaused: boolean('scans_paused').default(false),
  lastEditedAt: timestamp('last_edited_at', { withTimezone: true }).defaultNow(),
});

export const scans = pgTable('scans', {
  id: uuid('id').primaryKey().defaultRandom(),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  status: text('status').notNull().default('pending'),
  rawResultsCount: integer('raw_results_count'),
  scoredResultsCount: integer('scored_results_count'),
  apifyRunId: text('apify_run_id'),
  errorMessage: text('error_message'),
  costCents: integer('cost_cents'),
  triggeredBy: text('triggered_by'),
});

export const signals = pgTable('signals', {
  id: uuid('id').primaryKey().defaultRandom(),
  scanId: uuid('scan_id').notNull().references(() => scans.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  tweetId: text('tweet_id').notNull(),
  tweetUrl: text('tweet_url').notNull(),
  tweetText: text('tweet_text').notNull(),
  tweetPostedAt: timestamp('tweet_posted_at', { withTimezone: true }).notNull(),
  tweetLikes: integer('tweet_likes').default(0),
  tweetReplies: integer('tweet_replies').default(0),
  tweetRetweets: integer('tweet_retweets').default(0),
  authorUsername: text('author_username').notNull(),
  authorDisplayName: text('author_display_name'),
  authorUrl: text('author_url'),
  authorBio: text('author_bio'),
  authorFollowers: integer('author_followers'),
  authorFollowing: integer('author_following'),
  authorAccountAgeDays: integer('author_account_age_days'),
  authorVerified: boolean('author_verified').default(false),
  intentScore: integer('intent_score').notNull(),
  intentReason: text('intent_reason'),
  intentFlavor: text('intent_flavor'),
  relevanceScore: integer('relevance_score').notNull(),
  relevanceReason: text('relevance_reason'),
  recencyScore: integer('recency_score').notNull(),
  recencyReason: text('recency_reason'),
  totalScore: integer('total_score').notNull(),
  tier: text('tier').notNull(),
  matchExplanation: text('match_explanation'),
  autoDisqualified: boolean('auto_disqualified').default(false),
  disqualificationReason: text('disqualification_reason'),
  draftReply: text('draft_reply'),
  draftDm: text('draft_dm'),
  draftError: text('draft_error'),
  userMarkedIrrelevant: boolean('user_marked_irrelevant').default(false),
  userSaved: boolean('user_saved').default(false),
  feedbackText: text('feedback_text'),
});
